services:
  app:
    build: .
    container_name: prism_spring_app
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
      - redis
  db:
    image: postgres:17
    container_name: prism_spring_db
    environment:
      POSTGRES_DB: prism_spring
      POSTGRES_USER: your_pg_user
      POSTGRES_PASSWORD: your_pg_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    container_name: prism_spring_redis
    ports:
      - "6379:6379"
volumes:
  pgdata:
